//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VasthuApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerServiceDetail
    {
        public long Id { get; set; }
        public Nullable<long> CustomerServiceId { get; set; }
        public Nullable<long> ServiceId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Note { get; set; }
    
        public virtual CustomerService CustomerService { get; set; }
        public virtual ServiceMaster ServiceMaster { get; set; }
    }
}
