//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VasthuApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Remark { get; set; }
    }
}
